/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/ErrorMessage/403.vue')['default']
    404: typeof import('./src/components/ErrorMessage/404.vue')['default']
    500: typeof import('./src/components/ErrorMessage/500.vue')['default']
    ColSetting: typeof import('./src/components/ProTable/components/ColSetting.vue')['default']
    DetailDialog: typeof import('./src/components/OpenlayerBaseMapGD/components/DetailDialog.vue')['default']
    DialogInfo: typeof import('./src/components/global/DialogInfo.vue')['default']
    ECharts: typeof import('./src/components/ECharts/index.vue')['default']
    Grid: typeof import('./src/components/Grid/index.vue')['default']
    GridItem: typeof import('./src/components/Grid/components/GridItem.vue')['default']
    Img: typeof import('./src/components/Upload/Img.vue')['default']
    Imgs: typeof import('./src/components/Upload/Imgs.vue')['default']
    ImportExcel: typeof import('./src/components/ImportExcel/index.vue')['default']
    Index_fix: typeof import('./src/components/SacaleAuto/index_fix.vue')['default']
    Index_old: typeof import('./src/components/SacaleAuto/index_old.vue')['default']
    Lend: typeof import('./src/components/OpenlayerBaseMapGD/components/Lend.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    MapboxBaseMap: typeof import('./src/components/MapboxBaseMap/index.vue')['default']
    MapLend: typeof import('./src/components/MapboxBaseMap/components/MapLend.vue')['default']
    OpenlayerBaseMapGD: typeof import('./src/components/OpenlayerBaseMapGD/index.vue')['default']
    OpenlayerBaseMapTDT: typeof import('./src/components/OpenlayerBaseMapTDT/index.vue')['default']
    Pagination: typeof import('./src/components/ProTable/components/Pagination.vue')['default']
    PopupCommon: typeof import('./src/components/OpenlayerBaseMapGD/components/popup/PopupCommon.vue')['default']
    ProTable: typeof import('./src/components/ProTable/index.vue')['default']
    QuillEditor: typeof import('./src/components/RichText/QuillEditor/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SacaleAuto: typeof import('./src/components/SacaleAuto/index.vue')['default']
    SearchForm: typeof import('./src/components/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./src/components/SearchForm/components/SearchFormItem.vue')['default']
    SelectDetailDialog: typeof import('./src/components/OpenlayerBaseMapGD/components/SelectDetailDialog.vue')['default']
    SelectFilter: typeof import('./src/components/SelectFilter/index.vue')['default']
    SelectIcon: typeof import('./src/components/SelectIcon/index.vue')['default']
    SetTokenDialog: typeof import('./src/components/OpenlayerBaseMapGD/components/SetTokenDialog.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    SwitchBaseLayer: typeof import('./src/components/OpenlayerBaseMapGD/components/SwitchBaseLayer.vue')['default']
    SwitchDark: typeof import('./src/components/SwitchDark/index.vue')['default']
    Tab: typeof import('./src/components/MapboxBaseMap/components/Tab.vue')['default']
    TableColumn: typeof import('./src/components/ProTable/components/TableColumn.vue')['default']
    TreeFilter: typeof import('./src/components/TreeFilter/index.vue')['default']
    WangEditor: typeof import('./src/components/WangEditor/index.vue')['default']
  }
}
